services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull qwen2.5:1.5b && wait" ]

  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data: